Repository auth0/idtoken-verifier, pull requests merged in 2021-05, with the labels that each got.

#120 Remove inconsistencies in verify method's callback invocations
  src/index.js
  test/helper/token-validation.js
  test/token-verification.test.js
Labels: CH: Fixed

#131 Pin crypto-js to 3.3.0
  package-lock.json
  package.json
Labels: CH: Security, review:tiny

#132 Release v2.1.2
  CHANGELOG.md
  docs/IdTokenVerifier.html
  docs/global.html
  docs/index.html
  docs/index.js.html
  package.json
  src/telemetry.js
Labels: review:tiny
